lesson_10 Done
qarber/hillel_qa_automation pull request #5
Opened 2023-11-29 22:19 UTC by qarber

2023-11-30 17:11 UTC, Art-auto commented on async_task.js
> +//     const getResponse = await fetch(url);
```suggestion
//     const getResponse = await request.getRequest(url);
```
варто було перевикористати створену функцію з api_helper

2023-11-30 17:12 UTC, Art-auto commented on async_task.js
> +//     const getResponse = await fetch(url);
Розкоментуй свою реалізацію, чому вона закоментована?

2023-11-30 17:13 UTC, Art-auto commented on async_task.js
> +//         delete rest.title; // Видалення властивості title
```suggestion
```
зайва дія, ти вже видалив всі title в попередньому рядку

2023-11-30 17:14 UTC, artem-s-test commented on async_task.js
> +//             const makePostRequest = await fetch(url,{
```suggestion
//             const makePostRequest = await request.postRequest(url,{
```
тут також варто було використати готову функцію

2023-11-30 17:15 UTC, artem-s-test requested changes
Виправ відповідно до коментарів

2023-12-03 21:11 UTC, qarber commented on async_task.js
> +//     const getResponse = await fetch(url);
@Art-auto 
замінив на 19й рядок на 
const getResponse = await request.getRequest(url);

АЛЕ тепер помилка в консолі

![image](https://github.com/qarber/hillel_qa_automation/assets/147742705/7cbc4402-b986-4e2f-ab8a-2d25b1c6b986)

2023-12-03 21:23 UTC, qarber commented on async_task.js
> +//             const makePostRequest = await fetch(url,{
@Art-auto 
тут в мене після заміни 49 строки в консолі та сама помилка що і з get запитом
Error during POST request: TypeError: makePostRequest.json is not a function

![image](https://github.com/qarber/hillel_qa_automation/assets/147742705/8d69da7f-4ba3-4c11-b67d-362c21e9609b)

2023-12-06 20:39 UTC, qarber commented
I will do new PR with fixes

2023-12-06 20:39 UTC, closed without merging